<<<<<<< Updated upstream
# Generated by Django 5.2.5 on 2025-08-30 10:57
=======
# Generated by Django 5.2.5 on 2025-08-30 09:14
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='cricket', max_length=100),
        ),
    ]
