# Generated by Django 5.2.4 on 2025-08-30 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_reports', models.IntegerField(default=0)),
                ('pending_reports', models.IntegerField(default=0)),
                ('validated_reports', models.IntegerField(default=0)),
                ('rejected_reports', models.IntegerField(default=0)),
                ('air_pollution_count', models.IntegerField(default=0)),
                ('water_pollution_count', models.IntegerField(default=0)),
                ('noise_pollution_count', models.IntegerField(default=0)),
                ('waste_management_count', models.IntegerField(default=0)),
                ('deforestation_count', models.IntegerField(default=0)),
                ('wildlife_conservation_count', models.IntegerField(default=0)),
                ('climate_change_count', models.IntegerField(default=0)),
                ('other_count', models.IntegerField(default=0)),
                ('low_severity_count', models.IntegerField(default=0)),
                ('medium_severity_count', models.IntegerField(default=0)),
                ('high_severity_count', models.IntegerField(default=0)),
                ('critical_severity_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('report_type', models.CharField(choices=[('air_pollution', 'Air Pollution'), ('water_pollution', 'Water Pollution'), ('noise_pollution', 'Noise Pollution'), ('waste_management', 'Waste Management'), ('deforestation', 'Deforestation'), ('wildlife_conservation', 'Wildlife Conservation'), ('climate_change', 'Climate Change'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('reporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reporter_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence score (0-1)')),
                ('verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='heatmap_rep_latitud_38992c_idx'), models.Index(fields=['report_type'], name='heatmap_rep_report__69d1ab_idx'), models.Index(fields=['status'], name='heatmap_rep_status_98e235_idx'), models.Index(fields=['created_at'], name='heatmap_rep_created_3452cf_idx')],
            },
        ),
    ]
