# Generated by Django 5.2.4 on 2025-08-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clerk_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
