# Generated by Django 5.2.4 on 2025-08-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalanalysis',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the environmental report'),
        ),
    ]
