# Generated by Django 5.2.5 on 2025-08-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_environmentalanalysis_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalanalysis',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude coordinate of the location', null=True),
        ),
        migrations.AddField(
            model_name='environmentalanalysis',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude coordinate of the location', null=True),
        ),
    ]
