# Generated by Django 5.2.5 on 2025-08-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_environmentalanalysis_latitude_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='environmentalanalysis',
            index=models.Index(fields=['-created_at'], name='dashboard_e_created_66e652_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentalanalysis',
            index=models.Index(fields=['risk_level'], name='dashboard_e_risk_le_c0ab7a_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentalanalysis',
            index=models.Index(fields=['status'], name='dashboard_e_status_f2ccf0_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentalanalysis',
            index=models.Index(fields=['risk_level', 'status'], name='dashboard_e_risk_le_e9b1d5_idx'),
        ),
    ]
