# Generated by Django 5.2 on 2025-08-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_environmentalanalysis_created_by'),
        ('dashboard', '0006_environmentalanalysis_created_by_and_more'),
    ]

    operations = [
    ]
